### ISSUE TITLE
Sound is broken by 921adb6c

### ISSUE THREAD

**Issue by stevecotton** [20kly/20kly#1]
Commit 921adb6c applied the spelling-fix from Debian's snd_disabled_typo.patch. But the Debian patch fixed two bugs:
* the typo
* the code being at file scope, and therefore running before the pygame.mixer has been loaded

The second bug results in 921adb6c always disabling the sound (at least on Debian systems). It can be fixed by applying the full Debian patch, which I've done in my  stevecotton:version1.4/debian_sound_patch branch.

**Comment by jwhitham** [comment]
Sound should be working again on all platforms in the newer version.
