### ISSUE TITLE
ttf-dejavu-core no longer available on deb-based Linux

### ISSUE THREAD

**Issue by hosiet** [20kly/20kly#3]
https://github.com/20kly/20kly/blob/a2a99eed4cc78dc1a5ccc7d7476a1ccbf2a00ab7/lib20k/primitives.py#L177

Current path of DejavuSans font is `/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf`, provided by package fonts-dejavu-core. Package ttf-dejavu-core has been dropped to unify font package naming.

Package fonts-dejavu-core is available since 2013.
Package ttf-dejavu-core was dropped in 2020.

**Comment by jwhitham** [comment]
Updated the file location in commit 29d0f92edf517595539925593c62b022e8593ceb
